// <auto-generated />
using CoincidenceApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CoincidenceApp.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0-preview.4.20220.10");

            modelBuilder.Entity("CoincidenceApp.Models.Tesaduf.SonDeger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("GelenDeger")
                        .HasColumnType("TEXT");

                    b.Property<long>("Sayac")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SonDegerler");
                });

            modelBuilder.Entity("CoincidenceApp.Models.Tesaduf.TesadufModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("GelenDeger")
                        .HasColumnType("TEXT");

                    b.Property<long>("Sayac")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("TesadufModels");
                });

            modelBuilder.Entity("CoincidenceApp.Models.Tesaduf.Zaman", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Dakika")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Gun")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Saat")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Saniye")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Zamanlar");
                });
#pragma warning restore 612, 618
        }
    }
}
